---
title: Bartolome Soccer Academy
timezone: Europe/Berlin
collections:
  news-items:
    title: News Items
    output: false
  posts:
    title: Posts
    output: true
  programs:
    title: Programs
    output: false
  uploads:
    title: Uploads
    output: true
version: v1
description: Bartlomé Soccer Academy offers a wide range of programs including 1 on
  1 and Small Group private sessions, Large Group Soccer Courses, Team & Coaches Clinics
  and week long Skills Camps. Rest assured, we have what you're looking for!
favicon: assets/images/logo.svg
tv: 4.5.3
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
jekyll_get:
  data: team
  json: https://18f.gsa.gov/hub/api/team/
