# Site settings
title: Bartolome Soccer Academy
version: "v1"
description: ""
favicon: assets/images/logo.svg
# baseurl: "http://astroloft.github.io/bsa" # the subpath of your site, e.g. /blog
# url: "http://astroloft.github.io/bsa" # the base hostname & protocol for your site

# Tachyons Version
tv: "4.5.3"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Jekyll Get TK
jekyll_get:
  data: team
  json: 'https://18f.gsa.gov/hub/api/team/'
