---
title: Bartolome Soccer Academy
timezone: UTC
collections:
  news-items:
    title: News Items
    output: false
  posts:
    title: Posts
    output: true
  programs:
    title: Programs
    output: false
  uploads:
    title: Uploads
    output: true
version: v1
description: ''
favicon: assets/images/logo.svg
tv: 4.5.3
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
jekyll_get:
  data: team
  json: https://18f.gsa.gov/hub/api/team/
